### ISSUE TITLE
MissingPluginException but i can see flutter_webview_plugin module in my project

### ISSUE THREAD

**Issue by manondidi** [fluttercommunity/flutter_webview_plugin#244]
Dart Error: Unhandled exception:
    MissingPluginException(No implementation found for method launch on channel flutter_webview_plugin)

**Comment by manondidi** [comment]
android

**Comment by manondidi** [comment]
add flutter into a exiting android project

**Comment by manondidi** [comment]
MissingPluginException(No implementation found for method close on channel flutter_webview_plugin)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:291:7)
    <asynchronous suspension>
    #1      FlutterWebviewPlugin.close (package:flutter_webview_plugin/src/base.dart:154:48)
    <asynchronous suspension>
    #2      _WebviewScaffoldState.dispose (package:flutter_webview_plugin/src/webview_scaffold.dart:84:22)
    #3      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:3878:12)
    #4      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1709:13)
    #5      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
    #6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3733:14)
    #7      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
    #8      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
    #9      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4826:14)
    #10     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
    #11     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
    #12     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3733:14)
    #13     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
    #14     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
    #15     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4826:14)
    #16     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
    #17     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
    #18     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4826:14)
    #19     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
    #20     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
    #21     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4826:14)
    #22     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
    #23     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
    #24     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4826:14)
    #25     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
    #26     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
    #27     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3733:14)
    #28     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
    #29     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
    #30     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3733:14)
    #31     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
    #32     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
    #33     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3733:14)
    #34     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
    #35     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
    #36     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4826:14)
    #37     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
    #38     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
    #39     ComponentElement

**Comment by manondidi** [comment]
i can give you my source code  if you leave email

**Comment by charafau** [comment]
that looks strange, what is your plugin version? try to run `flutter clean` maybe remove `.dart_tool` and get packages again.

**Comment by manondidi** [comment]
> that looks strange, what is your plugin version? try to run `flutter clean` maybe remove `.dart_tool` and get packages again.

add flutter into a exiting android project

  flutter_webview_plugin: ^0.3.0+2

did you try use flutter_webview_plugin in a exiting program add into flutter?

**Comment by manondidi** [comment]
> that looks strange, what is your plugin version? try to run `flutter clean` maybe remove `.dart_tool` and get packages again.

it work fine in a flutter project but not in a exiting project add into flutter

**Comment by manondidi** [comment]
还不只是这个原因

> that looks strange, what is your plugin version? try to run `flutter clean` maybe remove `.dart_tool` and get packages again.

i fixed this problem,but ...
i think it is maybe a bug in a exiting project add into flutter
i add flutter into my project by https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps
but i dont use flutterView or createFragment
i create a activity extand FlutterFragmentActivity
MissingPluginException(No implementation found for method close on channel flutter_webview_plugin)

i fixed it by

app.gradle
implementation project(':flutter_webview_plugin')
my activity
class ShopActivity : FlutterFragmentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        GeneratedPluginRegistrant.registerWith(this)
        FlutterWebviewPlugin.registerWith(this.registrarFor("com.flutter_webview_plugin.FlutterWebviewPlugin"))
}
}
why it happend? can you fix it without FlutterWebviewPlugin.registerWith???

because i dont use flutterview or flutterfragment?

thanks
