### ISSUE TITLE
The plugin flutter_webview_plugin could not be built due to the issue above

### ISSUE THREAD

**Issue by vAugagneur** [fluttercommunity/flutter_webview_plugin#634]
## System info

Issue occurs on: Android 
Plugin version: 0.3.10+1
Flutter doctor output:

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale fr-FR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!

```

## Steps to Reproduce

1. run : flutter build appbundle --release

## Logs

```
[        ] Running Gradle task 'assembleAarRelease'... (completed in 1,5s)
[   +1 ms] ✓ Built build/app/outputs/repo.
[        ] Building plugin flutter_webview_plugin...
[   +3 ms] Running Gradle task 'assembleAarRelease'...
[        ] gradle.properties already sets `android.enableR8`
[  +15 ms] "flutter apk" took 93 621ms.
The plugin flutter_webview_plugin could not be built due to the issue above.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:726:7)
#2      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#3      _rootRunBinary (dart:async/zone.dart:1146:38)
#4      _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#5      _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#6      Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#7      Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#8      Future._completeError (dart:async/future_impl.dart:532:5)
#9      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:580:7)
#10     _rootRun (dart:async/zone.dart:1126:13)
#11     _CustomZone.run (dart:async/zone.dart:1023:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

**Comment by ywanhzy** [comment]
Building plugin flutter_webview_plugin...
The plugin flutter_webview_plugin could not be built due to the issue above.
Running Gradle task 'assembleAarRelease'...

**Comment by WhiteSnowGirl** [comment]
Building plugin webview_flutter...
The plugin webview_flutter could not be built due to the issue above.
Running Gradle task 'assembleAarRelease'...                            -

**Comment by adarshchithran-mmt** [comment]
Same issue when creating a release apk. Creating a release signed APK by importing the /android  works though.

**Comment by fallenlord** [comment]
same problem here

**Comment by ZurMaD** [comment]
Same here

**Comment by chamilab** [comment]
same problem here.

**Comment by MahdiPishguy** [comment]
same problem here.

**Comment by DwijeshMishra** [comment]
Building plugin webview_flutter...
The plugin webview_flutter could not be built due to the issue above.
Running Gradle task 'assembleAarRelease'...

**Comment by cqzongjian** [comment]
The same problem.

**Comment by xiejibiao** [comment]
I also encounter this situation. Does anyone know how to solve it?

**Comment by adsizmusa** [comment]
I  have the same problem. How do I solve this problem. do you have idea
