### ISSUE TITLE
Flutter for web can not use flutter_webview_plugin

### ISSUE THREAD

**Issue by praphawit** [fluttercommunity/flutter_webview_plugin#651]
my code

`import 'package:flutter/material.dart';
import 'package:flutter_webview_plugin/flutter_webview_plugin.dart';

// ignore: prefer_collection_literals
void main() {
  // WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
}
class MyApp extends StatelessWidget {
  // final _webViewPlugin = FlutterWebviewPlugin();
  String filePath = 'files/test.html';

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter WebView Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      routes: {
        '/': (_) => new WebviewScaffold(
              url: "https://www.google.com",
              appBar: new AppBar(
                title: const Text('Widget webview'),
              ),
              withZoom: true,
              hidden: true,
              
            ),
      },
    );
  }
}
`
![image](https://user-images.githubusercontent.com/56682262/72578244-17339700-3908-11ea-83e5-35608239c29e.png)

**Comment by d3xt3r2909** [comment]
I have the same issue :)

**Comment by Gabrielhn** [comment]
Same here!

**Comment by villematti** [comment]
I have the same issue and this is what I see on Chrome console:

```
DevTools failed to parse SourceMap: chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map

natives.dart:14 Overflow on channel: flutter_webview_plugin.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
AR @ natives.dart:14
(anonymous) @ plugin_registry.dart:84
(anonymous) @ async_patch.dart:307
$2 @ async_patch.dart:332
Z @ async_patch.dart:237
O4 @ plugin_registry.dart:78
eN @ plugin_registry.dart:78
eval @ VM940:3
C4 @ window.dart:215
Kv @ binding.dart:175
ob @ binding.dart:224
(anonymous) @ platform_channel.dart:146
(anonymous) @ async_patch.dart:307
$2 @ async_patch.dart:332
Z @ async_patch.dart:237
J0 @ platform_channel.dart:145
f6 @ platform_channel.dart:145
(anonymous) @ platform_channel.dart:329
(anonymous) @ async_patch.dart:307
$2 @ async_patch.dart:332
Z @ async_patch.dart:237
OI @ base.dart:172
np @ base.dart:172
I_ @ bc_login_widget.dart:58
eval @ VM1076:3
Pt @ main.dart.js:28662
wJ @ framework.dart:977
$0 @ ink_well.dart:788
Af @ recognizer.dart:182
e1 @ recognizer.dart:168
A1 @ tap.dart:486
vQ @ tap.dart:264
A_ @ tap.dart:199
rj @ recognizer.dart:470
eval @ VM1109:3
Gl @ pointer_router.dart:76
$2 @ pointer_router.dart:117
U @ linked_hash_map.dart:207
w9 @ pointer_router.dart:115
Bd @ pointer_router.dart:101
ie @ binding.dart:218
Ne @ binding.dart:198
pe @ binding.dart:156
Io @ binding.dart:86
eval @ VM953:3
Jy @ pointer_binding.dart:129
eval @ VM944:3
$1 @ pointer_binding.dart:465
$1 @ pointer_binding.dart:430
$1 @ pointer_binding.dart:195
acn @ js_helper.dart:2017
(anonymous) @ js_helper.dart:2049...

js_helper.dart:1342 Uncaught MissingPluginException(No implementation found for method close on channel flutter_webview_plugin)
    at Object.c (http://localhost:5001/main.dart.js:1853:3)
    at http://localhost:5001/main.dart.js:35868:15
    at Xw.a (http://localhost:5001/main.dart.js:3127:71)
    at Xw.$2 (http://localhost:5001/main.dart.js:20744:23)
    at WZ.$1 (http://localhost:5001/main.dart.js:20736:30)
    at VW.Ql (http://localhost:5001/main.dart.js:21637:41)
    at VW.tE (http://localhost:5001/main.dart.js:21639:30)
    at Ur.$0 (http://localhost:5001/main.dart.js:21095:13)
    at Object.nN (http://localhost:5001/main.dart.js:3228:41)
    at L.lR (http://localhost:5001/main.dart.js:21023:3)
c @ js_helper.dart:1342
$0 @ async_patch.dart:693
abj @ schedule_microtask.dart:43
abs @ schedule_microtask.dart:52
$1 @ async_patch.dart:51
acn @ js_helper.dart:2017
(anonymous) @ js_helper.dart:2049
childList (async)
$1 @ async_patch.dart:64
a3Z @ async_patch.dart:29
lc @ zone.dart:1187
be @ zone.dart:1401
cf @ future_impl.dart:42
$1 @ binding.dart:177
Mg @ main.dart.js:24884
Jv @ channel_buffers.dart:128
eval @ VM1074:3
Gs @ channel_buffers.dart:73
ts @ channel_buffers.dart:55
AR @ channel_buffers.dart:138
(anonymous) @ plugin_registry.dart:84
(anonymous) @ async_patch.dart:307
$2 @ async_patch.dart:332
Z @ async_patch.dart:237
O4 @ plugin_registry.dart:78
eN @ plugin_registry.dart:78
eval @ VM940:3
C4 @ window.dart:215
Kv @ binding.dart:175
ob @ binding.dart:224
(anonymous) @ platform_channel.dart:146
(anonymous) @ async_patch.dart:307
$2 @ async_patch.dart:332
Z @ async_patch.dart:237
J0 @ platform_channel.dart:145
f6 @ platform_channel.dart:145
(anonymous) @ platform_channel.dart:329
(anonymous) @ async_patch.dart:307
$2 @ async_patch.dart:332
Z @ async_patch.dart:237
OI @ base.dart:172
np @ base.dart:172
I_ @ bc_login_widget.dart:58
eval @ VM1076:3
Pt @ main.dart.js:28662
wJ @ framework.dart:977
$0 @ ink_well.dart:788
Af @ recognizer.dart:182
e1 @ recognizer.dart:168
A1 @ tap.dart:486
vQ @ tap.dart:264
A_ @ tap.dart:199
rj @ recognizer.dart:470
eval @ VM1109:3
Gl @ pointer_router.dart:76
$2 @ pointer_router.dart:117
U @ linked_hash_map.dart:207
w9 @ pointer_router.dart:115
Bd @ pointer_router.dart:101
ie @ binding.dart:218
Ne @ binding.dart:198
pe @ binding.dart:156
Io @ binding.dart:86
eval @ VM953:3
Jy @ pointer_binding.dart:129
eval @ VM944:3
$1 @ pointer_binding.dart:465
$1 @ pointer_binding.dart:430
$1 @ pointer_binding.dart:195
acn @ js_helper.dart:2017
(anonymous) @ js_helper.dart:2049...
```

Does this have something to do with the fact that Flutter Web runs on beta channel or what does that might mean?

**Comment by vgrepo** [comment]
Same here!

**Comment by d3xt3r2909** [comment]
Any updates, it's blocking me from implementing my app and plugins on web.

**Comment by shinriyo** [comment]
why do you need it use for Flutter for web?
Don't you iframe?
