### ISSUE TITLE
flutter_webview_plugin with flutter_boost running under android, found exception

### ISSUE THREAD

**Issue by stoneLee81** [fluttercommunity/flutter_webview_plugin#750]
plugin used：
flutter_webview_plugin: ^0.3.10+2
flutter_boost:
git:
url: 'https://github.com/alibaba/flutter_boost.git'
ref: 'v1.12.13-hotfixes'
running okey under flutter env, but when I build with aar and run it under android, it threw below exceptions:
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method close on channel flutter_webview_plugin)
#0 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319)

#1 FlutterWebviewPlugin.close (package:flutter_webview_plugin/src/base.dart:238)
#2 _WebviewWidgetState.initState (package:flutter_module/src/widgets/webview_plugin.dart:50)
#3 StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355)
#4 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#5 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#6 Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#7 SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#8 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#9 Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#10 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#11 Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#12 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#13 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#14 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#15 Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#16 SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#17 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#18 Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#19 SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#20 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#21 Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#22 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#23 Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#24 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#25 StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381)
#26 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#27 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#28 Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#29 SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#30 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#31 Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#32 SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#33 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#34 Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#35 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#36 Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#37 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#38 StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381)
#39 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#40 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#41 Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#42 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#43 Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#44 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#45 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#46 Element.inflateWidg
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method close on channel flutter_webview_plugin)
#0 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319)

#1 FlutterWebviewPlugin.close (package:flutter_webview_plugin/src/base.dart:238)
#2 _WebviewScaffoldState.initState (package:flutter_webview_plugin/src/webview_scaffold.dart:93)
#3 StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355)
#4 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#5 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#6 Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#7 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#8 Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#9 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#10 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#11 ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4617)
#12 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#13 MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5551)
#14 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#15 Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#16 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#17 Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#18 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#19 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#20 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#21 Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#22 SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#23 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#24 Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#25 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#26 Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#27 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#28 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#29 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#30 Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#31 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#32 Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#33 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#34 StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381)
#35 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#36 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#37 Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#38 SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
#39 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#40 Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
#41 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
#42 Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#43 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
#44 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
#45 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
#46 Element.updateChild (package:flutt
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method launch on channel flutter_webview_plugin)
#0 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319)

#1 FlutterWebviewPlugin.launch (package:flutter_webview_plugin/src/base.dart:225)
#2 _WebviewScaffoldState.build. (package:flutter_webview_plugin/src/webview_scaffold.dart:156)
#3 _WebviewPlaceholderRender.notifyRect (package:flutter_webview_plugin/src/webview_scaffold.dart:246)
#4 _WebviewPlaceholderRender.paint (package:flutter_webview_plugin/src/webview_scaffold.dart:256)
#5 RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219)
#6 PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184)
#7 RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2508)
#8 RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:396)
#9 RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219)
#10 PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184)
#11 RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123)
#12 _RenderInkFeatures.paint (package:flutter/src/material/material.dart:530)
#13 RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219)
#14 PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184)
#15 RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123)
#16 PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:384)
#17 RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1755)
#18 RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219)
#19 PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184)
#20 RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2508)
#21 RenderFlex.paint (package:flutter/src/rendering/flex.dart:948)
#22 RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219)
#23 PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184)
#24 RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70)
#25 RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219)
#26 PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184)
#27 RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123)
#28 RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219)
#29 PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184)
#30 RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123)
#31 RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219)
#32 PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135)
#33 PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95)
#34 PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:201)
#35 PaintingContext.paintChild (package:flutter/src/rendering/object.dart:182)
#36 RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123)
#37 RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219)
#38 PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184)
#39 RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123)
#40 PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:384)
#41 PaintingContext.pushOpacity (package:flutter/src/rendering/object.dart:569)
#42 RenderAnimatedOpacity.paint (package:flutter/src/rendering/proxy_box.dart:923)
#43 RenderObject._paintWithContext (package:flutter/src/rendering/obje

**Comment by stoneLee81** [comment]
Does it support v1.12.13-hotfixes flutter boost?
