### ISSUE TITLE
I am running on web and getting this error. Error: MissingPluginException(No implementation found for method close on channel flutter_webview_plugin)

### ISSUE THREAD

**Issue by Zeeshan90** [fluttercommunity/flutter_webview_plugin#900]
## System info

Issue occurs on: iOS / Android / both
Plugin version: latest
Flutter doctor output:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.0, on macOS 11.2.2 20D80 darwin-x64, locale en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)

• No issues found!

## Steps to Reproduce
Simply just run it on web and the page doesn't load and through an exception. 

## Logs

[+4371 ms] Error: MissingPluginException(No implementation found for method close on channel flutter_webview_plugin)
                        at Object.throw_ [as throw] (http://localhost:53868/dart_sdk.js:5334:11)
                        at MethodChannel._invokeMethod (http://localhost:53868/packages/flutter/src/services/system_channels.dart.lib.js:954:21)
                        at _invokeMethod.next (<anonymous>)
                        at http://localhost:53868/dart_sdk.js:39032:33
                        at _RootZone.runUnary (http://localhost:53868/dart_sdk.js:38889:58)
                        at _FutureListener.thenAwait.handleValue (http://localhost:53868/dart_sdk.js:33875:29)
                        at handleValueCallback (http://localhost:53868/dart_sdk.js:34435:49)
                        at Function._propagateToListeners (http://localhost:53868/dart_sdk.js:34473:17)
                        at _Future.new.[_completeWithValue] (http://localhost:53868/dart_sdk.js:34315:23)
                        at async._AsyncCallbackEntry.new.callback (http://localhost:53868/dart_sdk.js:34338:35)
                        at Object._microtaskLoop (http://localhost:53868/dart_sdk.js:39176:13)
                        at _startMicrotaskLoop (http://localhost:53868/dart_sdk.js:39182:13)
                        at http://localhost:53868/dart_sdk.js:34689:9
[   +6 ms] Error: MissingPluginException(No implementation found for method launch on channel flutter_webview_plugin)
               at Object.throw_ [as throw] (http://localhost:53868/dart_sdk.js:5334:11)
               at MethodChannel._invokeMethod (http://localhost:53868/packages/flutter/src/services/system_channels.dart.lib.js:954:21)
               at _invokeMethod.next (<anonymous>)
               at http://localhost:53868/dart_sdk.js:39032:33
               at _RootZone.runUnary (http://localhost:53868/dart_sdk.js:38889:58)
               at _FutureListener.thenAwait.handleValue (http://localhost:53868/dart_sdk.js:33875:29)
               at handleValueCallback (http://localhost:53868/dart_sdk.js:34435:49)
               at Function._propagateToListeners (http://localhost:53868/dart_sdk.js:34473:17)
               at _Future.new.[_completeWithValue] (http://localhost:53868/dart_sdk.js:34315:23)
               at async._AsyncCallbackEntry.new.callback (http://localhost:53868/dart_sdk.js:34338:35)
               at Object._microtaskLoop (http://localhost:53868/dart_sdk.js:39176:13)
               at _startMicrotaskLoop (http://localhost:53868/dart_sdk.js:39182:13)
               at http://localhost:53868/dart_sdk.js:34689:9

**Comment by diaz-wmg** [comment]
This does not work on web flutter (at least yet).

**Comment by rodrigoschaefer** [comment]
Same here on android
